# 服务
server:
  port: 50318


# 日志
logging:
  path: /u01/ferry/logs/client/

spring:
  profiles:
    include:
      - soap
      - doc
  # dataSource
  datasource:
    url: jdbc:mysql://106.13.78.137:3306/ferry
    username: ferry
    password: ferry
    driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
      host: 106.13.78.137
      port: 6379
      database: 3
      timeout: 5000ms
      password: redis
      client-name: ferry
      token-period: 900
      jedis:
        pool:
          max-active: 50
          max-idle: 20
          min-idle: 2
          max-wait: 3000ms
