spring:
  profiles:
    active: ${activeProfile}
  cache:
    redis:
      cache-null-values: true
      key-prefix: 'ferry:'
      use-key-prefix: true


server:
  api-login-uri: /api/login
  api-logout-uri: /api/logout
  form-login-uri: /login
  need-form-login-uri: /swagger**
