spring:
  profiles:
    active: ${activeProfile}
  cache:
    redis:
      cache-null-values: true
      key-prefix: 'ferry:'
      use-key-prefix: true


server:
  login-url: /api/login
  logout-url: /logout
