# 服务
server:
  port: 80
  session-timeout: 30
  tomcat:
    max-threads: 500
    uri-encoding: UTF-8


# 日志
logging:
  path: log/core/
  level:
    root: INFO
    cn.org.ferry : DEBUG




# mybatis
mybatis:
#  type-handlers-package: cn.org.ferry.system.mybatis.handler
  mapperLocations: classpath:cn/org/ferry/**/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
mapper:
  mappers: cn.org.ferry.system.mybatis.BaseMapper


pagehelper:
  helperDialect: mysql   # 指定数据库分页类型
  reasonable: true    # 页码<=0 查询第一页，页码>=总页数查询最后一页
  supportMethodsArguments: true   # 支持通过 Mapper 接口参数来传递分页参数
  params: count=countSql


# dataSource
spring:
  datasource:
    url: jdbc:mysql://47.100.232.59:3306/ferry
    username: ferry
    password: ferry
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 47.100.232.59
    port: 6379
    database: 3
    timeout: 5000ms
    password: redis
    client-name: ferry
    token-period: 900
    jedis:
      pool:
        max-active: 50
        max-idle: 20
        min-idle: 2
        max-wait: 3000ms
  liquibase:
    enabled: false

# 自定义的配置属性
ferry:
  upload: /u01/ferry/upload
  cors:
    allowedOrigins: "*"
    allowedHeaders: DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,If-Modified-Since,Cache-Control,Content-Type,_token
    allowedMethod: GET,POST,OPTIONS,DELETE,PUT
    maxAge: 1800
    url: "/api/**"
