# dataSource
spring:
  profiles:
    active: ${activeProfile}

# mybatis
mybatis:
  mapper-locations: classpath:cn/org/ferry/**/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true   # 开启驼峰映射
    cache-enabled: true
#mapper:
#  mappers: cn.org.ferry.system.mybatis.BaseMapper


pagehelper:
  helperDialect: mysql   # 指定数据库分页类型
  reasonable: true    # 页码<=0 查询第一页，页码>=总页数查询最后一页
  supportMethodsArguments: true   # 支持通过 Mapper 接口参数来传递分页参数
  params: count=countSql
