# 服务
server:
  port: 6688
  session-timeout: 30
  tomcat:
    max-threads: 500
    uri-encoding: UTF-8


# 日志
logging:
  path: log/
  level:
    root: INFO
    cn.org.ferry : DEBUG
    io.swagger.models.parameters.AbstractSerializableParameter: ERROR


# dataSource
spring:
  datasource:
    url: jdbc:mysql://47.100.232.59:3306/ferry
    username: ferry
    password: ferry
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 47.100.232.59
    port: 6379
    database: 3
    timeout: 5000ms
    password: redis
    client-name: ferry
    token-period: 900
    jedis:
      pool:
        max-active: 50
        max-idle: 20
        min-idle: 2
        max-wait: 3000ms
  liquibase:
    enabled: false

# actuator 配置参数
management:
  endpoint:
    shutdown:
      enabled: false   # 禁用接口关闭 Spring Boot
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"        # 打开所有的监控点
        exclude: shutdown   # 禁用关机服务
      base-path: /actuator  # 定制监控点路径，默认为 /actuator
# 定制 actuator 信息
info:
  app:
    name: ferry
    author: ferry
    email: ferry_sy@163.com
    desciption: 人生而自由，却无往不在枷锁之中

# 自定义的配置属性
ferry:
  upload: /u01/ferry/upload
  swagger:
    enabled: true
  cxf:
    path: /ws
  cors:
    allowedOrigins: "*"
    allowedHeaders: DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,If-Modified-Since,Cache-Control,Content-Type,_token
    allowedMethod: GET,POST,OPTIONS,DELETE,PUT
    maxAge: 1800
    url: "/api/**"
  filter:
    paths: "/swagger,/actuator/**"
