# 服务
server:
  port: 8888
  session-timeout: 30
  tomcat:
    max-threads: 500
    uri-encoding: UTF-8


# 日志
logging:
  path: /u01/ferry/logs/
  level:
    root: DEBUG
    cn.org.ferry : DEBUG
    io.swagger.models.parameters.AbstractSerializableParameter: ERROR


# dataSource
spring:
  datasource:
#    url: jdbc:oracle:thin:@localhost:1521:XE
    url: jdbc:mysql://127.0.0.1:3306/ferry
#    driver-class-name: oracle.jdbc.OracleDriver
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ferry
    password: ferry
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 5000ms
#    password: ferry
    client-name: ferry
    jedis:
      pool:
        max-active: 50
        max-idle: 5
        min-idle: 0
        max-wait: 3000ms
  liquibase:
    enabled: false



# mybatis
mybatis:
  mapper-locations: classpath:cn/org/ferry/**/mapper/*Mapper.xml
  #  type-aliases-package: "cn.org.ferry.sys.dto"
  configuration:
    jdbc-type-for-null: 'null'
    map-underscore-to-camel-case: true   # 开启驼峰映射
    cache-enabled: true


pagehelper:
  reasonable: true    # 页码<=0 查询第一页，页码>=总页数查询最后一页
  supportMethodsArguments: true   # 支持通过 Mapper 接口参数来传递分页参数
  params: count=countSql


# actuator 配置参数
management:
  endpoint:
    shutdown:
      enabled: false   # 禁用接口关闭 Spring Boot
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"        # 打开所有的监控点
        exclude: shutdown   # 禁用关机服务
      base-path: /actuator  # 定制监控点路径，默认为 /actuator
# 定制 actuator 信息
info:
  app:
    name: ferry
    author: ferry
    email: ferry_sy@163.com
    desciption: 人生而自由，却无往不在枷锁之中
